In [3]:
from evaluation import *
import numpy as np

In [6]:
data = np.random.randint(1000,size=(100,10))
print("原始数据集:\n",data)

原始数据集:
 [[684 768 124 464 808 187 639 724 887 223]
 [253 479 804  18 996 229 806 609 480  52]
 [ 89 930 564 756 306 799 187 418 320 564]
 [493 267 991 893 595 208 137 665 210 916]
 [ 19 931 203 410 830 867 329 690  79 121]
 [197 314 564  96 336 720 626 305 700  45]
 [986 291 569 954 438 936 987 932 358  62]
 [978 337 222 579 678 523 781 983 139 617]
 [961 669 926 223 864 903 903  89 799  51]
 [772 972 880  82 462 305 457 312 223 577]
 [325 303 732 297  64 303  20 950 931 329]
 [605 320 132 335 823 682 321 777 124 424]
 [283 744 450 533 821 655 797 555 269 753]
 [ 61 868 415  25 544 376 616 989 245 313]
 [ 96 996 817 926 877 104  70 193  67  78]
 [822 376 771 511 625 655 222 106 416 420]
 [304 366 259 470   8 818 346 685 880 213]
 [599 277 763 481   5 337 335 662 291 553]
 [863 497 933 591 539 716 406 992 604 612]
 [218 109 733 804 642 782 936 435 152 407]
 [391 459 674 368 739  12 492 283 504 419]
 [736 876 184 205 408 867   2 472 307 469]
 [685 274 475  79 794 759 191 294 388  11]
 [1

In [7]:
train_data,test_data = hold_out(data,0.8)
print('训练数据集:\n',train_data)
print('测试数据集:\n',test_data)

训练数据集:
 [[684 768 124 464 808 187 639 724 887 223]
 [253 479 804  18 996 229 806 609 480  52]
 [ 89 930 564 756 306 799 187 418 320 564]
 [493 267 991 893 595 208 137 665 210 916]
 [ 19 931 203 410 830 867 329 690  79 121]
 [197 314 564  96 336 720 626 305 700  45]
 [986 291 569 954 438 936 987 932 358  62]
 [978 337 222 579 678 523 781 983 139 617]
 [961 669 926 223 864 903 903  89 799  51]
 [772 972 880  82 462 305 457 312 223 577]
 [325 303 732 297  64 303  20 950 931 329]
 [605 320 132 335 823 682 321 777 124 424]
 [283 744 450 533 821 655 797 555 269 753]
 [ 61 868 415  25 544 376 616 989 245 313]
 [ 96 996 817 926 877 104  70 193  67  78]
 [822 376 771 511 625 655 222 106 416 420]
 [304 366 259 470   8 818 346 685 880 213]
 [599 277 763 481   5 337 335 662 291 553]
 [863 497 933 591 539 716 406 992 604 612]
 [218 109 733 804 642 782 936 435 152 407]
 [391 459 674 368 739  12 492 283 504 419]
 [736 876 184 205 408 867   2 472 307 469]
 [685 274 475  79 794 759 191 294 388  11]
 [1